### ISSUE TITLE
ProBro in VsCode over ssh to linux fails to open openedge-project.json

### ISSUE THREAD

**Issue by cverbiest** [BalticAmadeus/ProBro#573]
## To Reproduce

1. Connnect vscode over ssh to linux (Red Hat Enterprise Linux release 9.4 (Plow))
2. Open vscode workspace containing openedge-project.json
3. Open developers tools
4. Click on 'Probro'

## Expected behavior

No error readiing /home/domain/user/workspaces/develop/openedge-project.json

## Developer tools output

**Notice the missing / before home**

```
[Extension Host] [Info ] [undefined] return  true (r=true)
console.ts:137 [Extension Host] [Info ] [undefined] ctrl.refreshHandler post-refreshTestTree
console.ts:137 [Extension Host] [Info ] [undefined] ctrl.refreshHandler return (r=true)
console.ts:137 [Extension Host] useNew: false
console.ts:137 [Extension Host] execShell params :  
{connectionString: '-db /data/domain/develop/db/LISA   -H domain-develop-dbhost -S 4500 -ct 1', command: 'get_version'}
console.ts:137 [Extension Host] chmod +x /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/resources/oe/scripts/oe.sh
console.ts:137 [Extension Host] child stdout:
/home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/resources/oe/scripts/oe.sh called with
console.ts:137 [Extension Host] child stdout:
-p /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/resources/oe/src/oeSocket.p -clientlog /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/resources/oe/oeSocket.pro -pf /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/resources/oe/connectionPf.pf /usr/oe128
console.ts:137 [Extension Host] child stdout:
SERVER STARTED AT 2345
console.ts:137 [Extension Host] child stdout:
6
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: ENOENT: no such file or directory, open 'home/domain/user/workspaces/develop/openedge-project.json'
console.ts:137 [Extension Host] stack trace: Error: ENOENT: no such file or directory, open 'home/domain/user/workspaces/develop/openedge-project.json'
	at Object.readFileSync (node:fs:448:20)
	at gt (/home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:94:764)
	at f (/home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:110:2469)
	at /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:110:2066
	at Array.forEach (<anonymous>)
	at /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:110:2055
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
mainThreadExtensionService.ts:78 [BalticAmadeus.pro-bro]ENOENT: no such file or directory, open 'home/domain/user/workspaces/develop/openedge-project.json'
mainThreadExtensionService.ts:79 Error: ENOENT: no such file or directory, open 'home/domain/user/workspaces/develop/openedge-project.json'
	at Object.readFileSync (node:fs:448:20)
	at gt (/home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:94:764)
	at f (/home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:110:2469)
	at /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:110:2066
	at Array.forEach (<anonymous>)
	at /home/domain/user/.vscode-server/extensions/balticamadeus.pro-bro-1.7.0/out/extension.js:110:2055
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
﻿
```

##Desktop

 - OS: Red Hat Enterprise Linux release 9.4 (Plow)
 - ProBro Version v1.7.0
 - Other (VSC version, etc.)
Version: 1.93.1 (user setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

## Additional context
Actually trying to find out why ProBro is not connecting

**Comment by PauliusKu** [comment]
Merged
